language: node_js
script:
    - npm run build
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: .vuepress/dist
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master

