backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: ".vuepress/public/assets"
public_folder: "/assets"
site_url: https://whybotherts.com
logo_url: https://whybotherts.com/assets/ts-logo.png"
collections:
  - name: "pages"
    label: "Pages"
    folder: "."
    create: true
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
